mod 'puppet-nginx', '4.4.0'
mod 'puppetlabs-concat', '8.0.0'
mod 'puppetlabs-stdlib', '8.6.0'
mod 'samuelson-dockeragent', '1.0.0'
mod 'puppetlabs-docker', '6.0.2'
mod 'puppetlabs-apt', '9.0.2'
mod 'puppetlabs-powershell', '6.0.0'
mod 'puppetlabs-pwshlib', '0.10.3'
mod 'puppetlabs-reboot', '5.0.0'
mod 'puppetlabs/translate'
